services:
  - type: web
    name: removebg-photo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1  # Adjust size as needed
      - name: processed-disk
        mountPath: /app/processed
        sizeGB: 1  # Adjust size as needed
